#!/usr/bin/env python3

def numbers(line):
    n = set()

    for x in line.strip().split(" "):
        if x == "":
            continue
        n.add(int(x))
    return n


if __name__ == "__main__":
    with open("input.txt") as input_file:
        lines = input_file.readlines()

    total = 0

    for line in lines:
        _, sets = line.split(":")
        winning, card = sets.split("|")

        winning_numbers = numbers(winning)
        our_numbers = numbers(card)

        print(our_numbers)

        intersection = winning_numbers & our_numbers
        if len(intersection) > 0:
            total += 2 ** (len(intersection) - 1)

    print("Solution (part 1):", total)
